'use client';

import { useState } from 'react';
import type { ColumnDef } from '@tanstack/react-table';
import { Button } from '@/components/ui/button';
import { CmsDataTable } from '@/components/ui/cms-data-table';
import { SavedViewBar } from '@/components/ui/saved-view-bar';
import { StatusLabel } from '@/components/ui/status-label';
import { useI18n } from '@/i18n/use-i18n';
import { useListParams } from '@/hooks/use-list-params';
import { useOrders } from '../services/order-queries';
import type { JobOrder } from '@/mocks/fixtures/orders';
import { OrderDrawer } from './order-drawer';
import { CreateOrderModal } from './create-order-modal';
import { catalogLabel, occupationLabel } from '@/i18n/catalog-options';
import { getDomainLabel } from '@/i18n/domain-labels';
function orderColumns(t: ReturnType<typeof useI18n>['t'], formatDate: ReturnType<typeof useI18n>['formatDate']): ColumnDef<JobOrder>[] { return [{ accessorKey: 'code', header: t('orders.table.code'), cell: ({ row }) => <span className="font-semibold">{row.original.code}</span> }, { accessorKey: 'position', header: t('orders.table.position'), cell: ({ row }) => <div><p className="font-semibold">{occupationLabel(t, row.original.position)}</p><p className="text-xs text-text-muted">{occupationLabel(t, row.original.occupation)}</p></div> }, { accessorKey: 'client.name', header: t('orders.table.client'), cell: ({ row }) => row.original.client.name }, { accessorKey: 'industryLabel', header: t('orders.table.industry'), cell: ({ row }) => catalogLabel(t, row.original.industryLabel) }, { accessorKey: 'location', header: t('orders.table.location') }, { accessorKey: 'metrics.target', header: t('orders.table.target'), cell: ({ row }) => row.original.metrics.target }, { accessorKey: 'metrics.activeApplications', header: t('orders.table.active'), cell: ({ row }) => row.original.metrics.activeApplications }, { accessorKey: 'metrics.passed', header: t('orders.table.passed'), cell: ({ row }) => row.original.metrics.passed }, { accessorKey: 'metrics.supplied', header: t('orders.table.supplied'), cell: ({ row }) => row.original.metrics.supplied }, { accessorKey: 'deadline', header: t('orders.table.deadline'), cell: ({ row }) => formatDate(row.original.deadline, { dateStyle: 'short' }) }, { accessorKey: 'health', header: t('orders.table.health'), cell: ({ row }) => <StatusLabel tone={row.original.health === 'FILLED' ? 'success' : 'warning'}>{getDomainLabel(t, 'orderHealth', row.original.health)}</StatusLabel> }, { accessorKey: 'status', header: t('orders.table.status'), cell: ({ row }) => getDomainLabel(t, 'orderStatus', row.original.status) }]; }
export function OrderListPage() { const { t, formatDate } = useI18n(); const [createOpen, setCreateOpen] = useState(false); const { params, setQuery, setView, setSelectedId } = useListParams({ defaultView: 'all' }); const query = useOrders({ query: params.query, industry: params.view === 'all' ? undefined : params.view }); return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-accent">{t('orders.list.eyebrow')}</p><h1 className="mt-1 text-2xl font-bold text-text">{t('orders.list.title')}</h1><p className="mt-2 text-sm text-text-muted">{t('orders.list.description')}</p></div><Button variant="primary" onClick={() => setCreateOpen(true)}>{t('orders.list.add')}</Button></div><SavedViewBar><label className="flex min-w-0 flex-1 flex-wrap items-center gap-2 text-sm font-semibold text-text">{t('orders.list.searchLabel')}<input aria-label={t('orders.list.searchAria')} name="order-search" value={params.query} onChange={(event) => setQuery(event.target.value)} placeholder={t('orders.list.searchPlaceholder')} className="min-h-10 min-w-0 flex-1 rounded-control border border-border bg-panel px-3 font-normal sm:w-72 sm:flex-none" /></label><label className="flex items-center gap-2 text-sm text-text-muted">{t('orders.list.industryLabel')}<select aria-label={t('orders.list.industryAria')} name="order-industry" value={params.view} onChange={(event) => setView(event.target.value)} className="min-h-10 rounded-control border border-border bg-panel px-3"><option value="all">{t('orders.list.allIndustries')}</option><option value="Công nghệ thông tin">{t('orders.form.it')}</option><option value="Cơ khí">{t('orders.form.mechanical')}</option><option value="Điều dưỡng">{t('orders.form.nursing')}</option></select></label></SavedViewBar><CmsDataTable data={query.data?.items ?? []} columns={orderColumns(t, formatDate)} isLoading={query.isPending} error={query.error ? t('orders.list.loadError') : undefined} onRetry={() => void query.refetch()} emptyTitle={t('orders.list.empty')} getRowId={(row) => row.id} onRowClick={(row) => setSelectedId(row.id)} /><OrderDrawer orderId={params.selectedId} open={Boolean(params.selectedId)} onClose={() => setSelectedId(undefined)} /><CreateOrderModal open={createOpen} onClose={() => setCreateOpen(false)} /></div>; }
