import { describe, expect, it } from 'vitest';
import { JourneyCompletionService } from '../../src/modules/supply-journeys/application/journey-completion.service.js';
import type { JourneyRepository, JourneyScopeContext } from '../../src/modules/supply-journeys/application/supply-journey.service.js';
import type { SupplyJourneyEntity } from '../../src/modules/supply-journeys/domain/supply-journey.aggregate.js';

const context: JourneyScopeContext = { actorId: 'u1', teamId: 't1', scope: 'TEAM', requestId: 'r1', correlationId: 'c1' };
const entity = (status: SupplyJourneyEntity['status'] = 'ACTIVE'): SupplyJourneyEntity => ({ id: 'j1', candidateId: 'c1', applicationId: 'a1', templateVersionId: 'tv1', templateChecksum: `sha256:${'a'.repeat(64)}`, ownerUserId: 'u1', teamId: 't1', status, contextSnapshot: { residenceContext: 'OUTSIDE_JAPAN', caseType: 'NEW_ENTRY', visaRouteVersionId: null, sectorVersionId: null, occupationVersionId: null }, startedAt: new Date(), completedAt: null, cancelReason: null, idempotencyKey: 'k1', version: 1, milestones: [{ code: 'A', name: 'A', sequence: 1, dependencyCodes: [], status: 'NOT_STARTED', ownerUserId: 'u1', dueAt: null, completedAt: null, blockerParty: null, blockerReason: null, expectedResolution: null, waiveReason: null, waivedBy: null, waivedAt: null, notApplicableReason: null, checklistData: {}, evidenceRequirement: [], attemptNo: 1, version: 1 }], createdAt: new Date(), updatedAt: new Date() });
class Repo implements JourneyRepository { row = entity(); async withTransaction<T>(work: (repo: JourneyRepository, tx: unknown) => Promise<T>): Promise<T> { return work(this, {}); } async getApplicationContext() { return null; } async findEffectiveByCandidate() { return null; } async findByIdempotency() { return null; } async create() { return this.row; } async findScoped() { return this.row; } async updateStatus(_id: string, expectedVersion: number, status: SupplyJourneyEntity['status'], patch: { completedAt?: Date | null; cancelReason?: string | null }) { if (expectedVersion !== this.row.version) return null; this.row = { ...this.row, status, version: this.row.version + 1, completedAt: patch.completedAt ?? null, cancelReason: patch.cancelReason ?? null }; return this.row; } async list() { return [this.row]; } }
describe('journey completion', () => {
  it('blocks completion until milestones reach acceptable terminal states', async () => { const service = new JourneyCompletionService(new Repo()); await expect(service.complete('j1', 1, context)).rejects.toMatchObject({ code: 'JOURNEY_MILESTONES_INCOMPLETE' }); });
  it('records cancel reason and terminal transition', async () => { const repo = new Repo(); const service = new JourneyCompletionService(repo); const cancelled = await service.cancel('j1', 1, 'candidate withdrew', context); expect(cancelled.status).toBe('CANCELLED'); expect(cancelled.cancelReason).toBe('candidate withdrew'); });
});
