'use client';

import { useState } from 'react';
import type { ColumnDef } from '@tanstack/react-table';
import { Button } from '@/components/ui/button';
import { CmsDataTable } from '@/components/ui/cms-data-table';
import { SavedViewBar } from '@/components/ui/saved-view-bar';
import { StatusLabel } from '@/components/ui/status-label';
import { useI18n } from '@/i18n/use-i18n';
import { useListParams } from '@/hooks/use-list-params';
import { useClients } from '../services/client-queries';
import type { Client } from '../services/client-types';
import { ClientDrawer } from './client-drawer';
import { CreateClientModal } from './create-client-modal';
import { catalogLabel, organizationTypeLabel } from '@/i18n/catalog-options';
function clientColumns(t: ReturnType<typeof useI18n>['t'], formatDate: ReturnType<typeof useI18n>['formatDate']): ColumnDef<Client>[] { return [{ accessorKey: 'code', header: t('clients.table.code'), cell: ({ row }) => <span className="font-semibold">{row.original.code}</span> }, { accessorKey: 'name', header: t('clients.table.name'), cell: ({ row }) => <div><p className="font-semibold">{row.original.name}</p><p className="text-xs text-text-muted">{row.original.region}</p></div> }, { accessorKey: 'organizationType', header: t('clients.table.type'), cell: ({ row }) => organizationTypeLabel(t, row.original.organizationType) }, { accessorKey: 'industryLabels', header: t('clients.table.industry'), cell: ({ row }) => row.original.industryLabels.map((value) => catalogLabel(t, value)).join(', ') }, { accessorKey: 'owner.name', header: t('clients.table.owner'), cell: ({ row }) => row.original.owner.name }, { accessorKey: 'activeOrders', header: t('clients.table.activeOrders') }, { accessorKey: 'target', header: t('clients.table.target') }, { accessorKey: 'passed', header: t('clients.table.passed') }, { accessorKey: 'status', header: t('clients.table.status'), cell: ({ row }) => <StatusLabel tone={row.original.status === 'ACTIVE' ? 'success' : 'neutral'}>{t(row.original.status === 'ACTIVE' ? 'clients.table.activeStatus' : row.original.status === 'PROSPECT' ? 'clients.table.prospectStatus' : row.original.status === 'PAUSED' ? 'clients.list.paused' : 'clients.form.inactive')}</StatusLabel> }, { accessorKey: 'lastActivity', header: t('clients.table.lastActivity'), cell: ({ row }) => <span className="text-xs text-text-muted">{formatDate(row.original.lastActivity, { dateStyle: 'short' })}</span> }]; }
export function ClientListPage() { const { t, formatDate } = useI18n(); const [createOpen, setCreateOpen] = useState(false); const { params, setQuery, setView, setSelectedId } = useListParams({ defaultView: 'all' }); const query = useClients({ query: params.query, status: params.view === 'all' ? undefined : params.view.toUpperCase() }); return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-accent">{t('clients.list.eyebrow')}</p><h1 className="mt-1 text-2xl font-bold text-text">{t('clients.list.title')}</h1><p className="mt-2 text-sm text-text-muted">{t('clients.list.description')}</p></div><Button variant="primary" onClick={() => setCreateOpen(true)}>{t('clients.list.add')}</Button></div><SavedViewBar><label className="flex min-w-0 flex-1 flex-wrap items-center gap-2 text-sm font-semibold text-text">{t('clients.list.searchLabel')}<input aria-label={t('clients.list.searchAria')} name="client-search" value={params.query} onChange={(event) => setQuery(event.target.value)} placeholder={t('clients.list.searchPlaceholder')} className="min-h-10 min-w-0 flex-1 rounded-control border border-border bg-panel px-3 font-normal sm:w-72 sm:flex-none" /></label><label className="flex items-center gap-2 text-sm text-text-muted">{t('clients.list.statusLabel')}<select aria-label={t('clients.list.statusAria')} name="client-status" value={params.view} onChange={(event) => setView(event.target.value)} className="min-h-10 rounded-control border border-border bg-panel px-3"><option value="all">{t('clients.list.all')}</option><option value="active">{t('clients.list.active')}</option><option value="prospect">{t('clients.list.prospect')}</option><option value="paused">{t('clients.list.paused')}</option></select></label></SavedViewBar><CmsDataTable data={query.data?.items ?? []} columns={clientColumns(t, formatDate)} isLoading={query.isPending} error={query.error ? t('clients.list.loadError') : undefined} onRetry={() => void query.refetch()} emptyTitle={t('clients.list.empty')} getRowId={(row) => row.id} onRowClick={(row) => setSelectedId(row.id)} /><ClientDrawer clientId={params.selectedId} open={Boolean(params.selectedId)} onClose={() => setSelectedId(undefined)} /><CreateClientModal open={createOpen} onClose={() => setCreateOpen(false)} /></div>; }
