'use client';

import { useEffect, useState } from 'react';
import { EmptyState } from '@/components/ui/empty-state';
import { LoadingState } from '@/components/ui/loading-state';
import type { Client } from '../services/client-types';
import { useApplications } from '@/features/applications/services/application-queries';
import { useOrders } from '@/features/orders/services/order-queries';
import { StatusLabel } from '@/components/ui/status-label';
import { Button } from '@/components/ui/button';
import { useTabKeyboard } from '@/hooks/use-tab-keyboard';
import { useI18n } from '@/i18n/use-i18n';
import { catalogLabel, organizationTypeLabel } from '@/i18n/catalog-options';
import { occupationLabel } from '@/i18n/catalog-options';
import { getDomainLabel } from '@/i18n/domain-labels';

export const clientTabs = [
  { id: 'overview', key: 'clients.profile.tabs.overview' }, { id: 'orders', key: 'clients.profile.tabs.orders' }, { id: 'candidates', key: 'clients.profile.tabs.candidates' }, { id: 'contacts', key: 'clients.profile.tabs.contacts' }, { id: 'files', key: 'clients.profile.tabs.files' }, { id: 'history', key: 'clients.profile.tabs.history' }
] as const;
export type ClientTab = (typeof clientTabs)[number]['id'];

function statusKey(status: Client['status']) { return status === 'ACTIVE' ? 'clients.list.active' : status === 'PROSPECT' ? 'clients.list.prospect' : status === 'PAUSED' ? 'clients.list.paused' : 'clients.form.inactive'; }
function KpiCard({ label, value, detail }: { label: string; value: number; detail: string }) { return <section className="rounded-lg border border-border bg-panel p-4"><p className="text-sm text-text-muted">{label}</p><p className="mt-2 text-2xl font-bold text-text">{value}</p><p className="mt-1 text-xs text-text-muted">{detail}</p></section>; }
function InfoRow({ label, value }: { label: string; value: string }) { return <div><dt className="text-sm text-text-muted">{label}</dt><dd className="mt-1 font-semibold text-text">{value}</dd></div>; }

function OverviewTab({ client }: { client: Client }) {
  const { t, formatDate } = useI18n();
  return <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-lg border border-border bg-panel p-5"><h2 className="text-base font-bold text-text">{t('clients.profile.organization')}</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><InfoRow label={t('clients.profile.code')} value={client.code} /><InfoRow label={t('clients.profile.type')} value={organizationTypeLabel(t, client.organizationType)} /><InfoRow label={t('clients.profile.industry')} value={client.industryLabels.map((value) => catalogLabel(t, value)).join(', ')} /><InfoRow label={t('clients.profile.region')} value={client.region} /><InfoRow label={t('clients.profile.owner')} value={client.owner.name} /><InfoRow label={t('clients.profile.contact')} value={client.contactName ?? t('clients.profile.notUpdated')} /></dl></section><section className="rounded-lg border border-border bg-panel p-5"><h2 className="text-base font-bold text-text">{t('clients.profile.supply')}</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><InfoRow label={t('clients.profile.activeOrders')} value={`${client.activeOrders} ${t('orders.table.active')}`} /><InfoRow label={t('clients.profile.target')} value={`${client.target}`} /><InfoRow label={t('clients.profile.passed')} value={`${client.passed}`} /><InfoRow label={t('clients.profile.lastActivity')} value={formatDate(client.lastActivity)} /></dl><div className="mt-5 rounded-control border border-border bg-surface p-4"><p className="text-sm font-semibold text-text">{t('clients.profile.followUp')}</p><p className="mt-1 text-sm text-text-muted">{client.activeOrders > 0 ? t('clients.profile.followUpActive', { count: client.activeOrders }) : t('clients.profile.noActiveOrders')}</p></div></section><section className="rounded-lg border border-border bg-panel p-5 lg:col-span-2"><h2 className="text-base font-bold text-text">{t('clients.profile.notes')}</h2>{client.notes ? <p className="mt-3 max-w-3xl text-sm leading-6 text-text-muted">{client.notes}</p> : <p className="mt-3 text-sm text-text-muted">{t('clients.profile.noNotes')}</p>}</section></div>;
}

function SecondaryTab({ tab, client }: { tab: Exclude<ClientTab, 'overview'>; client: Client }) {
  const { t, formatDate, formatDateTime } = useI18n();
  const [files, setFiles] = useState<Array<{ id: string; name: string; uploadedAt: string }>>([]);
  const [channel, setChannel] = useState('');
  useEffect(() => { try { const storedFiles = window.localStorage.getItem(`cms-client-${client.id}-files`); const storedChannel = window.localStorage.getItem(`cms-client-${client.id}-channel`); if (storedFiles) setFiles(JSON.parse(storedFiles) as Array<{ id: string; name: string; uploadedAt: string }>); if (storedChannel) setChannel(storedChannel); } catch { /* Ignore malformed local demo state. */ } }, [client.id]);
  const addFile = (file: File) => { const next = [...files, { id: `local-${Date.now()}`, name: file.name, uploadedAt: new Date().toISOString() }]; setFiles(next); window.localStorage.setItem(`cms-client-${client.id}-files`, JSON.stringify(next)); };
  const saveChannel = (value: string) => { setChannel(value); window.localStorage.setItem(`cms-client-${client.id}-channel`, value); };
  const orders = useOrders({ query: client.name });
  const applications = useApplications({ query: client.name });
  const clientOrders = orders.data?.items.filter((order) => order.client.id === client.id) ?? [];
  const clientApplications = applications.data?.items.filter((application) => application.client.id === client.id) ?? [];
  if (tab === 'orders') return <div className="space-y-4"><section className="rounded-lg border border-border bg-panel p-5"><p className="text-sm text-text-muted">{t('clients.profile.ordersActive')}</p><p className="mt-2 text-3xl font-bold text-text">{client.activeOrders}</p><p className="mt-1 text-sm text-text-muted">{t('clients.profile.filteredOrders')}</p></section>{orders.isPending ? <LoadingState label={t('clients.profile.loadingOrders')} /> : clientOrders.length ? <div className="space-y-3">{clientOrders.map((order) => <article key={order.id} className="rounded-lg border border-border bg-panel p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-accent">{order.code}</p><h3 className="mt-1 font-bold text-text">{occupationLabel(t, order.position)}</h3><p className="mt-1 text-sm text-text-muted">{catalogLabel(t, order.industryLabel)} · {order.location} · {t('clients.profile.deadline', { date: formatDate(order.deadline) })}</p></div><StatusLabel tone={order.health === 'FILLED' ? 'success' : 'warning'}>{getDomainLabel(t, 'orderStatus', order.status)}</StatusLabel></div><p className="mt-3 text-sm text-text-muted">{t('clients.profile.passedSupplied', { passed: order.metrics.passed, supplied: order.metrics.supplied })}</p></article>)}</div> : <EmptyState title={t('clients.profile.noOrders')} description={t('clients.profile.noOrdersDescription')} />}</div>;
  if (tab === 'candidates') return <div className="space-y-4"><section className="rounded-lg border border-border bg-panel p-5"><p className="text-sm text-text-muted">{t('clients.profile.candidatesPassed')}</p><p className="mt-2 text-3xl font-bold text-text">{client.passed}</p><p className="mt-1 text-sm text-text-muted">{t('clients.profile.applicationsSource')}</p></section>{applications.isPending ? <LoadingState label={t('clients.profile.loadingCandidates')} /> : clientApplications.length ? <div className="overflow-x-auto rounded-lg border border-border bg-panel"><table className="w-full min-w-[38rem] text-left text-sm"><thead className="border-b border-border bg-surface text-xs uppercase tracking-wide text-text-muted"><tr><th className="px-4 py-3">{t('clients.profile.candidate')}</th><th className="px-4 py-3">{t('clients.profile.order')}</th><th className="px-4 py-3">{t('clients.profile.status')}</th><th className="px-4 py-3">{t('clients.profile.updated')}</th></tr></thead><tbody>{clientApplications.map((application) => <tr key={application.id} className="border-b border-border last:border-0"><td className="px-4 py-3"><p className="font-semibold text-text">{application.candidate.name}</p><p className="text-xs text-text-muted">{application.candidate.code}</p></td><td className="px-4 py-3 text-text">{application.order.code}</td><td className="px-4 py-3"><StatusLabel tone={application.status === 'PASSED' ? 'success' : application.status === 'FAILED' || application.status === 'WITHDRAWN' ? 'danger' : 'info'}>{getDomainLabel(t, 'applicationStatus', application.status)}</StatusLabel></td><td className="px-4 py-3 text-text-muted">{formatDate(application.lastActivityAt)}</td></tr>)}</tbody></table></div> : <EmptyState title={t('clients.profile.noCandidates')} description={t('clients.profile.noCandidatesDescription')} />}</div>;
  if (tab === 'contacts') return <section className="rounded-lg border border-border bg-panel p-5"><h2 className="text-base font-bold text-text">{t('clients.profile.primaryContact')}</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><InfoRow label={t('clients.profile.contact')} value={client.contactName ?? t('clients.profile.notUpdated')} /><InfoRow label={t('clients.profile.region')} value={client.region} /><div><dt className="text-sm text-text-muted">{t('clients.profile.channel')}</dt><dd className="mt-1"><input aria-label={t('clients.profile.channelAria')} name="client-contact-channel" value={channel} onChange={(event) => saveChannel(event.target.value)} placeholder={t('clients.profile.channelPlaceholder')} className="min-h-10 w-full rounded-control border border-border bg-panel px-3 text-sm" /></dd></div><InfoRow label={t('clients.profile.owner')} value={client.owner.name} /></dl><p className="mt-3 text-xs text-text-muted">{t('clients.profile.channelHint')}</p></section>;
  if (tab === 'files') return <div className="space-y-4"><section className="rounded-lg border border-border bg-panel p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-bold text-text">{t('clients.profile.filesTitle')}</h2>{client.notes ? <p className="mt-3 text-sm leading-6 text-text-muted">{client.notes}</p> : <p className="mt-3 text-sm text-text-muted">{t('clients.profile.noFileNote')}</p>}</div><label className="inline-flex min-h-10 cursor-pointer items-center rounded-control bg-accent px-4 text-sm font-semibold text-white">{t('clients.profile.addFile')}<input className="sr-only" type="file" name="client-files" aria-label={t('clients.profile.addFileAria')} onChange={(event) => { const file = event.target.files?.[0]; if (file) addFile(file); event.currentTarget.value = ''; }} /></label></div>{files.length ? <ul className="mt-4 space-y-2">{files.map((file) => <li key={file.id} className="flex items-center justify-between rounded-control border border-border bg-surface px-3 py-3 text-sm"><span className="font-semibold text-text">{file.name}</span><span className="text-xs text-text-muted">{formatDateTime(file.uploadedAt)} · {t('clients.profile.pendingFile')}</span></li>)}</ul> : <p className="mt-4 rounded-lg border border-dashed border-border p-4 text-sm text-text-muted">{t('clients.profile.noFiles')}</p>}</section></div>;
  return <section className="rounded-lg border border-border bg-panel p-5"><h2 className="text-base font-bold text-text">{t('clients.profile.recentActivity')}</h2><ol className="mt-4 border-l border-border pl-5"><li className="relative pb-2"><span className="absolute -left-[1.4rem] top-1.5 h-2 w-2 rounded-full bg-accent" /><p className="text-sm font-semibold text-text">{t('clients.profile.updatedClient')}</p><p className="mt-1 text-sm text-text-muted">{formatDateTime(client.lastActivity)}</p><p className="mt-2 text-sm text-text-muted">{client.notes ?? t('clients.profile.noActivityDescription')}</p></li></ol></section>;
}

export function ClientProfileContent({ client, activeTab, onTabChange, onEdit }: { client: Client; activeTab: ClientTab; onTabChange: (tab: ClientTab) => void; onEdit?: () => void }) {
  const { t, formatDateTime, formatPercent } = useI18n();
  const localizedOrganizationType = organizationTypeLabel(t, client.organizationType);
  const localizedIndustries = client.industryLabels.map((value) => catalogLabel(t, value));
  const handleTabKeyDown = useTabKeyboard(clientTabs.map(({ id }) => id), (value) => onTabChange(value as ClientTab));
  return <div className="space-y-6"><header className="flex flex-col gap-4 border-b border-border pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-accent">{client.code}</p><h1 className="mt-1 text-2xl font-bold text-text md:text-3xl">{client.name}</h1><p className="mt-2 text-sm text-text-muted">{localizedOrganizationType} · {client.region} · {t('clients.profile.owner')} {client.owner.name}</p><div className="mt-3 flex flex-wrap gap-2"><StatusLabel tone={client.status === 'ACTIVE' ? 'success' : client.status === 'PAUSED' ? 'warning' : 'neutral'}>{t(statusKey(client.status))}</StatusLabel>{localizedIndustries.map((industry) => <StatusLabel key={industry} tone="info">{industry}</StatusLabel>)}</div></div><div className="flex flex-wrap items-end gap-2"><Button variant="secondary" onClick={onEdit}>{t('clients.profile.edit')}</Button><div className="rounded-lg border border-border bg-surface px-4 py-3 text-sm"><p className="text-text-muted">{t('clients.profile.lastActivity')}</p><p className="mt-1 font-semibold text-text">{formatDateTime(client.lastActivity)}</p></div></div></header><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><KpiCard label={t('clients.profile.activeOrders')} value={client.activeOrders} detail={t('clients.profile.tracking')} /><KpiCard label={t('clients.profile.target')} value={client.target} detail={t('clients.profile.demand')} /><KpiCard label={t('clients.profile.passed')} value={client.passed} detail={t('clients.profile.totalPassed')} /><KpiCard label={t('clients.profile.rate')} value={client.target ? Math.round((client.passed / client.target) * 100) : 0} detail={formatPercent(client.target ? client.passed / client.target : 0) + ' · ' + t('clients.profile.comparedTarget')} /></section><nav className="-mx-1 overflow-x-auto border-b border-border" aria-label={t('clients.profile.tabsLabel')} role="tablist" onKeyDown={handleTabKeyDown}><div className="flex min-w-max gap-1 px-1">{clientTabs.map((tab) => <button key={tab.id} type="button" role="tab" data-tab-value={tab.id} tabIndex={activeTab === tab.id ? 0 : -1} aria-selected={activeTab === tab.id} onClick={() => onTabChange(tab.id)} className={`min-h-11 whitespace-nowrap border-b-2 px-3 text-sm font-semibold transition-colors ${activeTab === tab.id ? 'border-accent text-accent' : 'border-transparent text-text-muted hover:border-border hover:text-text'}`}>{t(tab.key)}</button>)}</div></nav>{activeTab === 'overview' ? <OverviewTab client={client} /> : <SecondaryTab tab={activeTab} client={client} />}</div>;
}
