import { DocumentDomainError } from '../../documents/domain/document.rules.js';
export interface RetentionRepository { activeHold(entityType: string, entityId: string): Promise<boolean>; createHold(input: { entityType: string; entityId: string; reason: string; placedBy: string }): Promise<Record<string, unknown>>; releaseHold(id: string, actorId: string): Promise<void>; findPurgeCandidates(policyCode: string, before: Date): Promise<Array<{ entityType: string; entityId: string }>>; markPurged(candidates: Array<{ entityType: string; entityId: string }>, actorId: string): Promise<void>; }
export class RetentionService {
  constructor(private readonly repository: RetentionRepository, private readonly purgeEnabled = false) {}
  async dryRun(policyCode: string, before: Date) { const candidates = await this.repository.findPurgeCandidates(policyCode, before); const held: Array<{ entityType: string; entityId: string }> = []; const eligible: Array<{ entityType: string; entityId: string }> = []; for (const candidate of candidates) (await this.repository.activeHold(candidate.entityType, candidate.entityId) ? held : eligible).push(candidate); return { policyCode, before: before.toISOString(), eligibleCount: eligible.length, heldCount: held.length, eligible, held, purgeEnabled: this.purgeEnabled }; }
  async execute(policyCode: string, before: Date, actorId: string, approvalId?: string) { if (!this.purgeEnabled) throw new DocumentDomainError('PURGE_DISABLED', 503); if (!approvalId?.trim()) throw new DocumentDomainError('PURGE_APPROVAL_REQUIRED', 403); const plan = await this.dryRun(policyCode, before); await this.repository.markPurged(plan.eligible, actorId); return { ...plan, executed: plan.eligibleCount }; }
  async placeHold(input: { entityType: string; entityId: string; reason: string; actorId: string }) { if (!input.reason.trim()) throw new DocumentDomainError('LEGAL_HOLD_REASON_REQUIRED'); return this.repository.createHold({ entityType: input.entityType, entityId: input.entityId, reason: input.reason.trim(), placedBy: input.actorId }); }
  async releaseHold(id: string, actorId: string) { return this.repository.releaseHold(id, actorId); }
}
