'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { SavedViewBar } from '@/components/ui/saved-view-bar';
import { SavedViewMenu } from '@/components/ui/saved-view-menu';
import { useCurrentUser } from '@/lib/auth/use-current-user';
import { useListParams } from '@/hooks/use-list-params';
import { useTabKeyboard } from '@/hooks/use-tab-keyboard';
import { useI18n } from '@/i18n/use-i18n';
import { candidateListIndustryOptions } from '@/i18n/catalog-options';
import { useCandidates, type CandidateView } from '../services/candidate-queries';
import { CandidateDrawer } from './candidate-drawer';
import { CandidateTable } from './candidate-table';
import { CreateCandidateModal } from './create-candidate-modal';
import { AddApplicationDialog } from '@/features/applications/components/add-application-dialog';
import { DuplicateReviewModal } from './duplicate-review-modal';
import { ImportCandidatesModal } from './import-candidates-modal';

const views = [
  ['all', 'candidates.views.all'], ['potential', 'candidates.views.potential'], ['new-unassigned', 'candidates.views.newUnassigned'], ['ready-to-match', 'candidates.views.readyToMatch'], ['applying', 'candidates.views.applying'], ['passed', 'candidates.views.passed'], ['supplying', 'candidates.views.supplying'], ['supplied', 'candidates.views.supplied'], ['paused', 'candidates.views.paused'], ['archived', 'candidates.views.archived'], ['missing-contact', 'candidates.views.missingContact'], ['missing-documents', 'candidates.views.missingDocuments'], ['duplicates', 'candidates.views.duplicates']
] as const;

const readinessOptions = [['all', 'candidates.list.all'], ['NOT_READY', 'candidates.filters.readiness.notReady'], ['READY_FOR_REVIEW', 'candidates.filters.readiness.review'], ['READY_FOR_INTERVIEW', 'candidates.filters.readiness.interview']] as const;
const contactabilityOptions = [['all', 'candidates.list.all'], ['CONTACTABLE', 'candidates.filters.contactability.contactable'], ['UNKNOWN', 'candidates.filters.contactability.unknown'], ['DO_NOT_CONTACT', 'candidates.filters.contactability.doNotContact']] as const;
const japaneseOptions = [['all', 'candidates.filters.japanese.all'], ['N2', 'candidates.filters.japanese.n2'], ['N3', 'candidates.filters.japanese.n3'], ['N4', 'candidates.filters.japanese.n4']] as const;
const ownerOptions = [['all', 'candidates.list.all'], ['u-recruiter', 'adminExtraNames.recruiter'], ['u-manager', 'adminExtraNames.manager'], ['u-coordinator', 'adminExtraNames.coordinator']] as const;
const recordOptions = [['all', 'candidates.list.active'], ['ARCHIVED', 'candidates.list.archived']] as const;
const experienceOptions = [['all', 'candidates.list.all'], ['0-2', 'candidates.list.years02'], ['3-5', 'candidates.list.years35'], ['6+', 'candidates.list.years6']] as const;

export function CandidateListPage({ initialView = 'potential' }: { initialView?: CandidateView }) {
  const { t } = useI18n();
  const [createOpen, setCreateOpen] = useState(false);
  const [importOpen, setImportOpen] = useState(false);
  const [duplicateOpen, setDuplicateOpen] = useState(false);
  const [candidateForOrder, setCandidateForOrder] = useState<string>();
  const currentUser = useCurrentUser();
  const { params, setQuery, setView, setSort, setSelectedId } = useListParams({ defaultView: initialView });
  const view = (views.some(([id]) => id === params.view) ? params.view : initialView) as CandidateView;
  const handleTabKeyDown = useTabKeyboard(views.map(([id]) => id), setView);
  const [industry = 'all', readiness = 'all', contactability = 'all', japaneseLevel = 'all', ownerId = 'all', recordStatus = 'all', occupation = '', skill = '', desiredLocation = '', source = '', experience = 'all'] = params.sort.split('|');
  const query = useCandidates({ query: params.query, view, industry: industry === 'all' ? undefined : industry, readiness: readiness === 'all' ? undefined : readiness, contactability: contactability === 'all' ? undefined : contactability, occupation: occupation || undefined, skill: skill || undefined, desiredLocation: desiredLocation || undefined, source: source || undefined, recordStatus: recordStatus === 'all' ? undefined : recordStatus, experience: experience === 'all' ? undefined : experience });
  const updateFilters = (next: { industry?: string; readiness?: string; contactability?: string; japaneseLevel?: string; ownerId?: string; recordStatus?: string; occupation?: string; skill?: string; desiredLocation?: string; source?: string; experience?: string }) => setSort([next.industry ?? industry, next.readiness ?? readiness, next.contactability ?? contactability, next.japaneseLevel ?? japaneseLevel, next.ownerId ?? ownerId, next.recordStatus ?? recordStatus, next.occupation ?? occupation, next.skill ?? skill, next.desiredLocation ?? desiredLocation, next.source ?? source, next.experience ?? experience].join('|'));
  const viewLabel = t((views.find(([id]) => id === view)?.[1] ?? 'candidates.views.potential') as Parameters<typeof t>[0]);
  const filteredCandidates = (query.data?.items ?? []).filter((candidate) => (japaneseLevel === 'all' || candidate.japaneseLevel === japaneseLevel) && (ownerId === 'all' || candidate.owner.id === ownerId) && (view === 'archived' ? candidate.recordStatus === 'ARCHIVED' : recordStatus === 'all' ? candidate.recordStatus === 'ACTIVE' : candidate.recordStatus === recordStatus));
  const optionLabel = (key: string) => t(key as Parameters<typeof t>[0]);

  return <div className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-accent">{t('candidates.list.eyebrow')}</p><h1 className="mt-1 text-2xl font-bold text-text">{t('candidates.list.title')}</h1><p className="mt-2 max-w-3xl text-sm text-text-muted">{t('candidates.list.description')}</p></div><div className="flex flex-wrap justify-end gap-2"><Button onClick={() => setImportOpen(true)}>{t('candidates.list.import')}</Button><Button onClick={() => setDuplicateOpen(true)}>{t('candidates.list.duplicateReview')}</Button><Button variant="primary" onClick={() => setCreateOpen(true)}>{t('candidates.list.add')}</Button></div></div>
    <section className="rounded-lg border border-border bg-panel p-4"><p className="text-sm font-semibold text-text">{viewLabel}</p><p className="mt-1 text-sm text-text-muted">{t('candidates.list.viewDescription')}</p></section>
    <SavedViewBar className="cms-candidate-filter-bar">
      <label className="flex min-w-0 flex-col items-stretch gap-2 text-sm font-semibold text-text">{t('candidates.list.searchLabel')}<input name="candidate-search" aria-label={t('candidates.list.searchLabel')} value={params.query} onChange={(event) => setQuery(event.target.value)} placeholder={t('candidates.list.searchPlaceholder')} className="min-h-10 min-w-0 w-full rounded-control border border-border bg-panel px-3 font-normal" /></label>
      <label className="flex min-w-0 flex-col items-stretch gap-2 text-sm text-text-muted">{t('candidates.list.industryLabel')}<select aria-label={t('candidates.list.industryAria')} name="nganh-ung-vien" value={industry} onChange={(event) => updateFilters({ industry: event.target.value })} className="min-h-10 min-w-0 w-full rounded-control border border-border bg-panel px-3">{candidateListIndustryOptions.map(({ value, key }) => <option key={value} value={value}>{t(key)}</option>)}</select></label>
      <label className="flex min-w-0 flex-col items-stretch gap-2 text-sm text-text-muted">{t('candidates.list.readinessLabel')}<select aria-label={t('candidates.list.readinessAria')} name="muc-san-sang-ho-so" value={readiness} onChange={(event) => updateFilters({ readiness: event.target.value })} className="min-h-10 min-w-0 w-full rounded-control border border-border bg-panel px-3">{readinessOptions.map(([id, key]) => <option key={id} value={id}>{optionLabel(key)}</option>)}</select></label>
      <label className="flex min-w-0 flex-col items-stretch gap-2 text-sm text-text-muted">{t('candidates.list.contactabilityLabel')}<select aria-label={t('candidates.list.contactabilityAria')} name="trang-thai-lien-he-ung-vien" value={contactability} onChange={(event) => updateFilters({ contactability: event.target.value })} className="min-h-10 min-w-0 w-full rounded-control border border-border bg-panel px-3">{contactabilityOptions.map(([id, key]) => <option key={id} value={id}>{optionLabel(key)}</option>)}</select></label>
      <label className="flex min-w-0 flex-col items-stretch gap-2 text-sm text-text-muted">{t('candidates.list.japaneseLabel')}<select aria-label={t('candidates.list.japaneseAria')} name="trinh-do-tieng-nhat" value={japaneseLevel} onChange={(event) => updateFilters({ japaneseLevel: event.target.value })} className="min-h-10 min-w-0 w-full rounded-control border border-border bg-panel px-3">{japaneseOptions.map(([id, key]) => <option key={id} value={id}>{optionLabel(key)}</option>)}</select></label>
      <label className="flex min-w-0 flex-col items-stretch gap-2 text-sm text-text-muted">{t('candidates.list.ownerLabel')}<select aria-label={t('candidates.list.ownerAria')} name="nguoi-phu-trach-ung-vien" value={ownerId} onChange={(event) => updateFilters({ ownerId: event.target.value })} className="min-h-10 min-w-0 w-full rounded-control border border-border bg-panel px-3">{ownerOptions.map(([id, key]) => <option key={id} value={id}>{optionLabel(key)}</option>)}</select></label>
      <label className="flex min-w-0 flex-col items-stretch gap-2 text-sm text-text-muted">{t('candidates.list.recordLabel')}<select aria-label={t('candidates.list.recordAria')} name="trang-thai-luu-tru-ung-vien" value={recordStatus} onChange={(event) => updateFilters({ recordStatus: event.target.value })} className="min-h-10 min-w-0 w-full rounded-control border border-border bg-panel px-3">{recordOptions.map(([id, key]) => <option key={id} value={id}>{optionLabel(key)}</option>)}</select></label>
      <label className="flex min-w-0 flex-col items-stretch gap-2 text-sm text-text-muted">{t('candidates.list.experienceLabel')}<select aria-label={t('candidates.list.experienceAria')} name="so-nam-kinh-nghiem" value={experience} onChange={(event) => updateFilters({ experience: event.target.value })} className="min-h-10 min-w-0 w-full rounded-control border border-border bg-panel px-3">{experienceOptions.map(([id, key]) => <option key={id} value={id}>{optionLabel(key)}</option>)}</select></label>
      <label className="flex min-w-0 flex-col items-stretch gap-2 text-sm text-text-muted">{t('candidates.list.occupationLabel')}<input aria-label={t('candidates.list.occupationAria')} name="loc-theo-nghe-nghiep" value={occupation} onChange={(event) => updateFilters({ occupation: event.target.value })} placeholder={t('candidates.list.occupationPlaceholder')} className="min-h-10 min-w-0 w-full rounded-control border border-border bg-panel px-3 font-normal" /></label>
      <label className="flex min-w-0 flex-col items-stretch gap-2 text-sm text-text-muted">{t('candidates.list.skillLabel')}<input aria-label={t('candidates.list.skillAria')} name="loc-theo-ky-nang" value={skill} onChange={(event) => updateFilters({ skill: event.target.value })} placeholder={t('candidates.list.skillPlaceholder')} className="min-h-10 min-w-0 w-full rounded-control border border-border bg-panel px-3 font-normal" /></label>
      <label className="flex min-w-0 flex-col items-stretch gap-2 text-sm text-text-muted">{t('candidates.list.locationLabel')}<input aria-label={t('candidates.list.locationAria')} name="loc-theo-khu-vuc-mong-muon" value={desiredLocation} onChange={(event) => updateFilters({ desiredLocation: event.target.value })} placeholder={t('candidates.list.locationPlaceholder')} className="min-h-10 min-w-0 w-full rounded-control border border-border bg-panel px-3 font-normal" /></label>
      <label className="flex min-w-0 flex-col items-stretch gap-2 text-sm text-text-muted">{t('candidates.list.sourceLabel')}<input aria-label={t('candidates.list.sourceAria')} name="loc-theo-nguon-ho-so" value={source} onChange={(event) => updateFilters({ source: event.target.value })} placeholder={t('candidates.list.sourcePlaceholder')} className="min-h-10 min-w-0 w-full rounded-control border border-border bg-panel px-3 font-normal" /></label>
      {currentUser.data ? <SavedViewMenu resource="candidates" user={currentUser.data} query={{ view, query: params.query, industry, readiness, contactability, japaneseLevel, ownerId, recordStatus, occupation, skill, desiredLocation, source, experience }} onApply={(saved) => { if (typeof saved.view === 'string') setView(saved.view); if (typeof saved.query === 'string') setQuery(saved.query); if (typeof saved.industry === 'string' && typeof saved.readiness === 'string' && typeof saved.contactability === 'string') setSort([saved.industry, saved.readiness, saved.contactability, typeof saved.japaneseLevel === 'string' ? saved.japaneseLevel : 'all', typeof saved.ownerId === 'string' ? saved.ownerId : 'all', typeof saved.recordStatus === 'string' ? saved.recordStatus : 'all', typeof saved.occupation === 'string' ? saved.occupation : '', typeof saved.skill === 'string' ? saved.skill : '', typeof saved.desiredLocation === 'string' ? saved.desiredLocation : '', typeof saved.source === 'string' ? saved.source : '', typeof saved.experience === 'string' ? saved.experience : 'all'].join('|')); }} /> : null}
    </SavedViewBar>
    <div className="flex flex-wrap gap-2" role="tablist" aria-label={t('candidates.list.tabListLabel')} onKeyDown={handleTabKeyDown}>{views.map(([id, key]) => <button key={id} type="button" role="tab" data-tab-value={id} tabIndex={view === id ? 0 : -1} aria-selected={view === id} onClick={() => setView(id)} className={`min-h-10 rounded-control border px-3 text-sm font-semibold ${view === id ? 'border-accent bg-accent text-white' : 'border-border bg-panel text-text-muted hover:text-text'}`}>{t(key as Parameters<typeof t>[0])}</button>)}</div>
    <CandidateTable candidates={filteredCandidates} isLoading={query.isPending} error={query.error ? t('candidates.list.loadingError') : undefined} onRetry={() => void query.refetch()} onRowClick={(candidate) => setSelectedId(candidate.id)} />
    <CandidateDrawer candidateId={params.selectedId} open={Boolean(params.selectedId)} onClose={() => setSelectedId(undefined)} onAddToOrder={(candidateId) => { setSelectedId(undefined); setCandidateForOrder(candidateId); }} />
    <AddApplicationDialog open={Boolean(candidateForOrder)} initialCandidateId={candidateForOrder} onClose={() => setCandidateForOrder(undefined)} /><CreateCandidateModal open={createOpen} onClose={() => setCreateOpen(false)} /><ImportCandidatesModal open={importOpen} onClose={() => setImportOpen(false)} /><DuplicateReviewModal open={duplicateOpen} onClose={() => setDuplicateOpen(false)} />
  </div>;
}
